// Package openapi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"strings"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xUwW7bOhD8FWLfOwqWk/SkmxIURYACLRoUPRg+bKi1zUAi2eUqsBHw3wtSkh3HDpoi",
	"uQiSdjnDnRnyCbTrvLNkJUD1BEzBOxsof/y0tPWkhZrPzI7TL+2skJX0it63RqMYZ8uH4Gz6F/SGOkxv",
	"/zOtoIL/ygN+OVRDOaDFGAtoKGg2PoFA9YxQ0dhTjJh5Q7XWrh/YPTtPLGbYqWnSU3aeoIIgbOwaYgEW",
	"OzpTiAUw/e4NUwPVIi0eW5fF1OruH0hLwtiPfsyoXUNnOTsKAddvoM0Ih/5T7rTA2JXLUEbaVPvmydbf",
	"b9UXp25aQqtq1hsjpKXnhPZIHAYtL2bz2TxtyHmy6A1UcDWbz66gAI+yyUOUOAiaP9aUhT125AdJzzYo",
	"bFtFWyPGrlX9607V08KMzzkFtw1U8NUEeVY8ytPlfP5PGaItdj6NvRgchovJqGqKQg2xGIuXJ8VriMsC",
	"jFAX/hbJKVlx7wIy4+5cSGvVmiDKrY6FyH0r7Ft5jWuvRfnyYGUW78IZA+7wkYIafVIed63D5kT11DWN",
	"MKSMgly7ZvdhZ3YvUBxy/A5b30jzUvcbJkw3Ax6s+vSBzK9eStfYqFHR95qcrzPSPRvZ5VTfEzJx3csG",
	"qsUyLuOfAAAA//82mXb1kAUAAA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
