// Package openapi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package openapi

// Account defines model for Account.
type Account struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// UnexpectedError defines model for UnexpectedError.
type UnexpectedError Error

// SaveAccountJSONBody defines parameters for SaveAccount.
type SaveAccountJSONBody Account

// SaveAccountRequestBody defines body for SaveAccount for application/json ContentType.
type SaveAccountJSONRequestBody SaveAccountJSONBody
